// Auto-generated by: supabase gen types typescript --local > src/shared/infrastructure/supabase/database.types.ts
// Re-run after every migration to keep this file in sync with the schema.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: Record<string, never>;
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
}
